#!/usr/bin/env python3
"""Embed a UTF-8 file as a Zig module (for nv_load_html_ref).

Usage:
  embed_html_zig.py <input_path> <output.zig> <module_comment_one_line>

Writes:
  pub const nv_todo_html_len: usize = N;
  pub const nv_todo_html_data: [nv_todo_html_len]u8 = .{ ... };
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_html_zig.py <input.html> <output.zig> <comment_one_line>\n"
        )
        return 2
    inp, outp, comment = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    n = len(data)
    lines: list[str] = []
    line = "    "
    for b in data:
        frag = f"0x{b:02x},"
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "    "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    esc = comment.replace("*/", "* /")
    out = (
        f"//! {esc}\n"
        "//! Generated by embed_html_zig.py — do not edit.\n"
        f"pub const nv_todo_html_len: usize = {n};\n"
        "pub const nv_todo_html_data: [nv_todo_html_len]u8 = .{\n"
        f"{body}\n"
        "};\n"
    )
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
