#!/usr/bin/env python3
"""Embed a UTF-8 file as a Rust module (byte array + length for nv_load_html_ref).

Usage:
  embed_html_rust.py <input_path> <output.rs> <module_doc_one_line>

Writes a module with:
  pub const NV_TODO_HTML_LEN: usize = N;
  pub static NV_TODO_HTML_DATA: [u8; N] = [ ... ];

NUL bytes in HTML are preserved.
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_html_rust.py <input.html> <output.rs> <doc_one_line>\n"
        )
        return 2
    inp, outp, doc = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    n = len(data)
    lines: list[str] = []
    line = "    "
    for b in data:
        frag = f"{b},"
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "    "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    esc = doc.replace("*/", "* /")
    out = (
        f"// {esc}\n"
        "//\n"
        "// Generated by embed_html_rust.py — do not edit.\n"
        "\n"
        f"pub const NV_TODO_HTML_LEN: usize = {n};\n"
        "\n"
        f"pub static NV_TODO_HTML_DATA: [u8; {n}] = [\n"
        f"{body}\n"
        "];\n"
    )
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
