#!/usr/bin/env python3
"""Embed a UTF-8 file as Swift (ContiguousArray<UInt8>) for nv_load_html_ref.

Usage:
  embed_html_swift.py <input_path> <output.swift> <comment_one_line>

Writes a small library module:
  public enum TodoHtmlEmbed {
    public static let byteCount: Int = N
    public static let bytes: ContiguousArray<UInt8> = ContiguousArray([ ... ])
  }
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_html_swift.py <input.html> <output.swift> <comment_one_line>\n"
        )
        return 2
    inp, outp, comment = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    n = len(data)
    lines: list[str] = []
    line = "    "
    for b in data:
        frag = f"{b},"
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "    "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    esc = comment.replace("*/", "* /")
    out = (
        "// SPDX-License-Identifier: Apache-2.0\n"
        f"// {esc}\n"
        "// Generated by embed_html_swift.py — do not edit.\n"
        "\n"
        "public enum TodoHtmlEmbed {\n"
        f"  public static let byteCount: Int = {n}\n"
        "  public static let bytes: ContiguousArray<UInt8> = ContiguousArray([\n"
        f"{body}\n"
        "  ])\n"
        "}\n"
    )
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
