#!/usr/bin/env python3
"""Embed a UTF-8 file as a C translation unit with byte array + accessors.

Usage:
  embed_html.py <input_path> <output.c> <symbol_prefix> [include_header]

include_header defaults to todo_html.h (declares <symbol_prefix>() and <symbol_prefix>_len()).

The array is stored as unsigned char and cast in the getter so embedded
NUL bytes in HTML are preserved (strlen would be wrong).
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) < 4 or len(sys.argv) > 5:
        sys.stderr.write(
            "usage: embed_html.py <input> <output.c> <symbol_prefix> [include_header]\n"
        )
        return 2
    inp, outp, sym = sys.argv[1], sys.argv[2], sys.argv[3]
    inc = sys.argv[4] if len(sys.argv) == 5 else "todo_html.h"
    if not sym or not sym.replace("_", "").isalnum():
        sys.stderr.write("embed_html.py: invalid symbol_prefix\n")
        return 2
    with open(inp, "rb") as f:
        data = f.read()
    lines = []
    line = "  "
    for i, b in enumerate(data):
        frag = "%d," % b
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "  "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    c = (
        "/* Auto-generated by embed_html.py - do not edit */\n"
        "#include <stddef.h>\n"
        "#include \"%s\"\n\n"
        "static const unsigned char %s_bytes[] = {\n%s\n};\n\n"
        "const char* %s(void) {\n"
        "  return (const char*)%s_bytes;\n"
        "}\n\n"
        "size_t %s_len(void) {\n"
        "  return sizeof(%s_bytes);\n"
        "}\n"
    ) % (inc, sym, body, sym, sym, sym, sym)
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(c)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
