#!/usr/bin/env python3
"""Embed a UTF-8 file as a Nim module with byte array + length (for nv_load_html_ref).

Usage:
  embed_html_nim.py <input_path> <output.nim> <module_comment_one_line>

Writes a module with:
  const nvTodoHtmlLen* = N
  const nvTodoHtmlData*: array[nvTodoHtmlLen, uint8] = [ ... ]

NUL bytes in HTML are preserved (unlike cstring-only embedding).
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_html_nim.py <input.html> <output.nim> <comment_one_line>\n"
        )
        return 2
    inp, outp, comment = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    n = len(data)
    lines: list[str] = []
    line = "  "
    for i, b in enumerate(data):
        frag = f"{b}u8,"
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "  "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    esc = comment.replace("*/", "* /")
    out = (
        f"## {esc}\n"
        "## Generated by embed_html_nim.py — do not edit.\n"
        f"const nvTodoHtmlLen* = {n}\n"
        "const nvTodoHtmlData*: array[nvTodoHtmlLen, uint8] = [\n"
        f"{body}\n"
        "]\n"
    )
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
