/* =============================================================================
 * nv_version_generated.h - Auto-generated version header
 *
 * Generated by CMake on Darwin
 * DO NOT EDIT - This file is regenerated on each build
 * =============================================================================
 */

#ifndef NV_VERSION_GENERATED_H
#define NV_VERSION_GENERATED_H

#define NV_VERSION_MAJOR 0
#define NV_VERSION_MINOR 1
#define NV_VERSION_PATCH 0
#define NV_VERSION_STRING "0.1.0"
#define NV_VERSION "0.1.0"
#define NV_BUILD_GIT_SHA "d94fd5e"

#endif /* NV_VERSION_GENERATED_H */
