#!/usr/bin/env python3
"""
Embed vue.global.prod.js into nv_vue_bundle.c for offline use (no CDN).
Usage: python3 embed_vue.py <path/to/vue.global.prod.js> <output.c>
"""
import sys
import os

def main():
    if len(sys.argv) < 3:
        print("Usage: embed_vue.py <vue.global.prod.js> <output.c>", file=sys.stderr)
        sys.exit(1)
    inp = sys.argv[1]
    out = sys.argv[2]
    if not os.path.isfile(inp):
        print(f"Error: {inp} not found. Run: curl -sL https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js -o {inp}", file=sys.stderr)
        sys.exit(1)
    with open(inp, "rb") as f:
        raw = f.read()
    try:
        js = raw.decode("utf-8")
    except UnicodeDecodeError:
        print("Error: vue file is not valid UTF-8", file=sys.stderr)
        sys.exit(1)
    # Escape for C string: \ -> \\, " -> \", newlines preserved as \n
    # Also break </script> so it doesn't close the HTML script tag
    js = js.replace("</script>", "</scr\" + \"ipt>")
    escaped = []
    for c in js:
        if c == "\\":
            escaped.append("\\\\")
        elif c == '"':
            escaped.append('\\"')
        elif c == "\n":
            escaped.append("\\n")
        elif c == "\r":
            escaped.append("\\r")
        elif c == "\t":
            escaped.append("\\t")
        else:
            escaped.append(c)
    s = "".join(escaped)
    # Split into chunks; avoid ending with \ (would cause line-continuation with next chunk)
    chunk_size = 4000
    chunks = []
    pos = 0
    while pos < len(s):
        end = min(pos + chunk_size, len(s))
        if end < len(s) and s[end - 1] == "\\":
            end -= 1  # don't end chunk with backslash
        chunks.append(s[pos:end])
        pos = end
    lines = [
        "/* Auto-generated by tools/embed_vue.py - do not edit */",
        "#include <stddef.h>",
        "",
        "const char* nv_vue_bundle(void) {",
        "  static const char s[] =",
    ]
    for i, chunk in enumerate(chunks):
        suffix = "" if i == len(chunks) - 1 else ""
        lines.append(f'    "{chunk}"{suffix}')
    lines.append("  ;")
    lines.append("  return s;")
    lines.append("}")
    lines.append("")
    lines.append("size_t nv_vue_bundle_len(void) {")
    lines.append(f"  return {len(js)};")
    lines.append("}")
    content = "\n".join(lines)
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write(content)
    print(f"Wrote {out} ({len(js)} bytes embedded)")

if __name__ == "__main__":
    main()
