#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path
from datetime import datetime

HEADER_LINE = "// ── FILE: {rel} ─────────────────────────\n"
DEPENDS_RE = re.compile(r'^\s*//\s*@depends\b')
VERSION_RE = re.compile(r'NV_VERSION\s*=\s*"([^"]+)"')

def read_text(p: Path) -> str:
    with open(p, "r", encoding="utf-8") as f:
        return f.read()

def write_text(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)

def parse_manifest(manifest: Path, src_dir: Path):
    if not manifest.exists():
        print(f"Missing manifest: {manifest}", file=sys.stderr)
        sys.exit(2)
    files = []
    for line in read_text(manifest).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        rel = line
        p = src_dir / rel
        if not p.exists():
            print(f"Missing source file listed in manifest: {rel}", file=sys.stderr)
            sys.exit(3)
        files.append((rel, p))
    if not files:
        print("Manifest is empty", file=sys.stderr)
        sys.exit(4)
    return files

def strip_depends(content: str) -> str:
    return "\n".join(l for l in content.splitlines() if not DEPENDS_RE.match(l)) + "\n"

def extract_version(constants_path: Path) -> str:
    txt = read_text(constants_path)
    m = VERSION_RE.search(txt)
    return m.group(1) if m else "0.0.0"

def build_iife(body: str) -> str:
    return (
        '(function(global) { "use strict";\n'
        + body +
        '})(typeof window !== "undefined" ? window : global);\n'
    )

def main():
    parser = argparse.ArgumentParser(description="Concatenate JS into a single bundle")
    parser.add_argument("--src", default="js/src", help="Source root directory containing build.manifest")
    parser.add_argument("--out", default="js/dist/nativeview.js", help="Output JS path")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    src_dir = (root / args.src).resolve()
    out_path = (root / args.out).resolve()
    manifest = src_dir / "build.manifest"

    files = parse_manifest(manifest, src_dir)

    # Deterministic timestamp: max mtime of inputs
    max_mtime = max(p.stat().st_mtime for _, p in files)
    ts = datetime.fromtimestamp(max_mtime).isoformat(timespec="seconds")

    # Version from core/constants.js
    const_path = src_dir / "core" / "constants.js"
    version = extract_version(const_path) if const_path.exists() else "0.0.0"

    sections = []
    total_lines = 0
    for rel, p in files:
        content = strip_depends(read_text(p))
        sections.append(HEADER_LINE.format(rel=rel))
        sections.append(content if content.endswith("\n") else content + "\n")
        total_lines += content.count("\n")

    body = "".join(sections)
    wrapped = build_iife(body)
    header = (
        f'// nativeview.js v{version} — built {ts}\n'
        f'// DO NOT EDIT — generated by tools/js_build.py from js/src/\n'
    )
    out_text = header + wrapped
    write_text(out_path, out_text)

    print(f"Wrote {out_path}")
    # Report sizes
    for rel, p in files:
        sz = p.stat().st_size
        print(f"{rel:35s} {sz:8d} B")
    print(f"Total lines: {total_lines}")

if __name__ == "__main__":
    main()
