# =============================================================================
# GenerateVersion.cmake - Generate version header for nativeview
#
# Generates nv_version_generated.h with version info from git and/or defaults
# =============================================================================

# Default version
set(NV_VERSION_MAJOR 0)
set(NV_VERSION_MINOR 1)
set(NV_VERSION_PATCH 0)

# Try to get git SHA if available
find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE NV_GIT_SHA
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
endif()

if(NOT NV_GIT_SHA)
  set(NV_GIT_SHA "unknown")
endif()

set(NV_VERSION_STRING "${NV_VERSION_MAJOR}.${NV_VERSION_MINOR}.${NV_VERSION_PATCH}")

# Generate the header file
set(NV_VERSION_HEADER_PATH "${CMAKE_BINARY_DIR}/include/nv_version_generated.h")

file(WRITE "${NV_VERSION_HEADER_PATH}" "/* =============================================================================
 * nv_version_generated.h - Auto-generated version header
 *
 * Generated by CMake on ${CMAKE_SYSTEM_NAME}
 * DO NOT EDIT - This file is regenerated on each build
 * =============================================================================
 */

#ifndef NV_VERSION_GENERATED_H
#define NV_VERSION_GENERATED_H

#define NV_VERSION_MAJOR ${NV_VERSION_MAJOR}
#define NV_VERSION_MINOR ${NV_VERSION_MINOR}
#define NV_VERSION_PATCH ${NV_VERSION_PATCH}
#define NV_VERSION_STRING \"${NV_VERSION_STRING}\"
#define NV_VERSION \"${NV_VERSION_STRING}\"
#define NV_BUILD_GIT_SHA \"${NV_GIT_SHA}\"

#endif /* NV_VERSION_GENERATED_H */
")

message(STATUS "Generated version header: ${NV_VERSION_STRING} (${NV_GIT_SHA})")
