#!/usr/bin/env python3
"""Embed a UTF-8 file as a Python module with bytes (for nv_load_html_ref).

Usage:
  embed_html_py.py <input_path> <output.py> <module_docstring_one_line>

Writes a module with:
  NV_TODO_HTML: bytes = bytes((...))

NUL bytes in HTML are preserved.
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_html_py.py <input.html> <output.py> <docstring_one_line>\n"
        )
        return 2
    inp, outp, doc = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    lines: list[str] = []
    line = "    "
    for i, b in enumerate(data):
        frag = f"{b},"
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "    "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    esc = doc.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    out = (
        f'"""{esc}\n'
        'Generated by embed_html_py.py — do not edit.\n'
        '"""\n'
        "from __future__ import annotations\n\n"
        "NV_TODO_HTML: bytes = bytes((\n"
        f"{body}\n"
        "))\n"
    )
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
