#!/usr/bin/env python3
"""Embed a UTF-8 file as a C# static byte array (for nv_load_html_ref).

Usage:
  embed_html_cs.py <input_path> <output.cs> <file_comment_one_line>

Writes a file with:
  public static class TodoHtmlEmbed { public static ReadOnlySpan<byte> Data => ...; }

NUL bytes in HTML are preserved.
"""
from __future__ import annotations

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_html_cs.py <input.html> <output.cs> <comment_one_line>\n"
        )
        return 2
    inp, outp, comment = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    lines: list[str] = []
    line = "        "
    for b in data:
        frag = f"{b}, "
        if len(line) + len(frag) > 100:
            lines.append(line.rstrip())
            line = "        "
        line += frag
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    esc = comment.replace("*/", "* /")
    out = (
        "// " + esc + "\n"
        "// Generated by embed_html_cs.py — do not edit.\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
        "\n"
        "namespace Jamharah.Todo;\n"
        "\n"
        "public static class TodoHtmlEmbed\n"
        "{\n"
        f"    public static ReadOnlySpan<byte> Data => _data;\n"
        f"    public static int Length => _data.Length;\n"
        "\n"
        "    private static readonly byte[] _data =\n"
        "    [\n"
        f"{body}\n"
        "    ];\n"
        "}\n"
    )
    import os

    out_dir = os.path.dirname(os.path.abspath(outp))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
